info:
  app:
    name: ParametaWS
    version: 1.0

spring:
  profiles:
    active: pro
  application:
    name: ${info.app.name}
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/prueba-parameta?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8078

propertiesApp:
  pathXsd : "employeeDescription.xsd"
  urlNameSpace: "http://www.parameta.com/api/web/ws/dto"

---
spring:
  profiles: dev
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}:%-30.30method:%-4.4line){cyan} %clr(%5p) %m%n%wEx"

---
spring:
  profiles: pro
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}:%-30.30method:%-4.4line){cyan} %clr(%5p) %m%n%wEx"